name = "Create Metropolis"
author = "AceKssler16"
version = "1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "495639662ffd21c67b2225384322cf74beff94922bb5226fa581effb1797b32e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.220"
