name = "Create Metropolis"
author = "AceKssler16"
version = "1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be564b1473548ac81e306b36aff71189af487b6dc855b1be036ba0c272e844ed"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
