#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Mar 10 23:41:15 CDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=12
shaderPack=VanillaPlus_v3.3.zip
